"""
Build per-business and per-user TF-IDF profile vectors from the per-review
TF-IDF matrix generated by vectorize.py.

Standalone counterpart to 03_profile_building/embedding/build_profiles.py --
same role (aggregate per-review vectors into group profiles + a
human-readable label), but reusing none of that pipeline's code.

Input:
    ../../data/interim/review_tfidf.npz         (from vectorize.py)
    ../../data/interim/review_tfidf_meta.csv    (from vectorize.py)
    ../../data/interim/tfidf_vectorizer.joblib  (from vectorize.py, for feature names)
Output:
    ../../data/profiles/business_tfidf_profiles.npz        (sparse, L2-normalized,
                                                              n_businesses x n_features)
    ../../data/profiles/business_tfidf_profiles_meta.csv   (business_id, n_reviews,
                                                              low_confidence, label)
    ../../data/profiles/user_tfidf_profiles.npz
    ../../data/profiles/user_tfidf_profiles_meta.csv

`label` is the top-6 TF-IDF terms by weight for that business/user -- unlike
the embedding pipeline's label step (profile_labels.build_group_labels),
which computes this same weighted-sum sparse matmul and then discards it
after extracting the label string, here the matrix itself IS the profile
representation used for similarity scoring, so nothing is computed twice.

Cold-start category-prior blending is not implemented here -- see
aggregation.py's module docstring for why that's a documented
simplification, not a regression.
"""
import numpy as np
import pandas as pd
import scipy.sparse as sp
import joblib

from aggregation import build_group_tfidf_profiles

ROOT = "../.."  # run this script from inside 03_profile_building/tfidf/
REVIEW_TFIDF_NPZ = f"{ROOT}/data/interim/review_tfidf.npz"
REVIEW_TFIDF_META = f"{ROOT}/data/interim/review_tfidf_meta.csv"
VECTORIZER_PATH = f"{ROOT}/data/interim/tfidf_vectorizer.joblib"

OUT_BUSINESS_TFIDF = f"{ROOT}/data/profiles/business_tfidf_profiles.npz"
OUT_BUSINESS_TFIDF_META = f"{ROOT}/data/profiles/business_tfidf_profiles_meta.csv"
OUT_USER_TFIDF = f"{ROOT}/data/profiles/user_tfidf_profiles.npz"
OUT_USER_TFIDF_META = f"{ROOT}/data/profiles/user_tfidf_profiles_meta.csv"

AGGREGATION_STRATEGY = "mean"      # "mean" | "recency" -- baseline default,
                                    # matches the embedding pipeline's
                                    # documented default (see its build_profiles.py)
DECAY_CONSTANT_DAYS = 30.0         # only used when AGGREGATION_STRATEGY == "recency"
MIN_REVIEWS_BUSINESS = 5
MIN_REVIEWS_USER = 3
TOP_N_LABEL_TERMS = 6


def labels_from_profile_matrix(profile_matrix, group_ids, feature_names, top_n=6):
    """Top-N terms by weight per row of a (n_groups, n_features) sparse
    matrix. Invariant to each row's own positive scaling (L2 normalization
    doesn't change which terms rank highest within a row), so this works
    identically whether called on the raw weighted-sum or the normalized
    profile matrix."""
    profile_matrix = profile_matrix.tocsr()
    feature_names = np.asarray(feature_names)
    labels = []
    for row_start, row_end in zip(profile_matrix.indptr[:-1], profile_matrix.indptr[1:]):
        row_idx = profile_matrix.indices[row_start:row_end]
        row_val = profile_matrix.data[row_start:row_end]
        if len(row_val) == 0:
            labels.append("")
            continue
        k = min(top_n, len(row_val))
        top_local = np.argpartition(-row_val, k - 1)[:k]
        top_local = top_local[np.argsort(-row_val[top_local])]
        labels.append(", ".join(feature_names[row_idx[top_local]]))
    return pd.DataFrame({"_group_id": group_ids, "label": labels})


def build_and_save(tfidf_matrix, meta, group_col, min_reviews, feature_names,
                    out_matrix_path, out_meta_path):
    profile_matrix, profile_meta = build_group_tfidf_profiles(
        tfidf_matrix, meta, group_col=group_col,
        strategy=AGGREGATION_STRATEGY, min_reviews=min_reviews,
        decay_constant=DECAY_CONSTANT_DAYS,
    )
    n_low_conf = int(profile_meta["low_confidence"].sum())
    print(f"  {len(profile_meta):,} {group_col}s, {n_low_conf:,} low-confidence "
          f"(< {min_reviews} reviews)")

    labels = labels_from_profile_matrix(
        profile_matrix, profile_meta[group_col].values, feature_names,
        top_n=TOP_N_LABEL_TERMS,
    )
    profile_meta["label"] = labels["label"].values

    sp.save_npz(out_matrix_path, profile_matrix)
    profile_meta.to_csv(out_meta_path, index=False)
    print(f"  Saved: {out_matrix_path}")
    print(f"  Saved: {out_meta_path}")


def main():
    print(f"Aggregation strategy: {AGGREGATION_STRATEGY}")
    print("Loading per-review TF-IDF matrix + meta ...")
    tfidf_matrix = sp.load_npz(REVIEW_TFIDF_NPZ).tocsr()
    meta = pd.read_csv(REVIEW_TFIDF_META)
    print(f"  {len(meta):,} reviews, {tfidf_matrix.shape[1]:,} features")

    vectorizer = joblib.load(VECTORIZER_PATH)
    feature_names = vectorizer.get_feature_names_out()

    print("Building business TF-IDF profiles ...")
    build_and_save(
        tfidf_matrix, meta, group_col="business_id", min_reviews=MIN_REVIEWS_BUSINESS,
        feature_names=feature_names,
        out_matrix_path=OUT_BUSINESS_TFIDF, out_meta_path=OUT_BUSINESS_TFIDF_META,
    )

    print("Building user TF-IDF profiles ...")
    build_and_save(
        tfidf_matrix, meta, group_col="user_id", min_reviews=MIN_REVIEWS_USER,
        feature_names=feature_names,
        out_matrix_path=OUT_USER_TFIDF, out_meta_path=OUT_USER_TFIDF_META,
    )


if __name__ == "__main__":
    main()
