"""
Build per-business and per-user profile embeddings from the per-review
embeddings generated by embeddings.py.

Input:
    ../../data/interim/review_embeddings.npy         (from embeddings.py)
    ../../data/interim/review_embeddings_meta.csv    (from embeddings.py)
    ../../data/interim/philly_reviews.parquet        (review text, for the TF-IDF label)
    ../../data/profiles/business_profiles.csv   (for the "categories" column,
                                              used by the cold-start prior)
Output:
    ../../data/profiles/business_embeddings.csv   (business_id, emb_0..emb_383,
                                                n_reviews, low_confidence, label)
    ../../data/profiles/user_embeddings.csv       (user_id, emb_0..emb_383,
                                                n_reviews, low_confidence, label)

`label` is a TF-IDF-derived human-readable string (top terms across ALL of
a profile's reviews, see profile_labels.py) -- an interpretability aid
since individual emb_ dimensions have no human meaning, unlike LDA's named
topic columns. It uses the exact same per-review weighting (mean/recency)
as the embedding itself, so it always describes what the embedding
represents.

Aggregation strategy and cold-start behavior are config below, not hardcoded
in aggregation.py -- change AGGREGATION_STRATEGY to "recency" to compare
against the "mean" baseline (default, matches the original simple mean-pool
behavior -- no regression) using the exact same downstream NDCG eval harness.

KNOWN CAVEAT (current dataset): data/profiles/business_profiles.csv already
has a review-count floor of 50, and user_profiles.csv a floor of 3 --
both filtered upstream in notebook 01. With the default thresholds below
(5 / 3), NO business or user in the current corpus will actually be flagged
low_confidence, so the cold-start blend is correctly implemented but inert
here. See aggregation.py's `_demo()` (run `python3 aggregation.py`) for a
synthetic check that the blend math itself is correct.
"""
import numpy as np
import pandas as pd

from aggregation import build_group_profiles, blend_with_category_prior
from profile_labels import fit_tfidf, build_group_labels

ROOT = "../.."  # run this script from inside 03_profile_building/embedding/
REVIEW_EMBEDDINGS_NPY = f"{ROOT}/data/interim/review_embeddings.npy"
REVIEW_EMBEDDINGS_META = f"{ROOT}/data/interim/review_embeddings_meta.csv"
REVIEWS_PARQUET = f"{ROOT}/data/interim/philly_reviews.parquet"
BUSINESS_PROFILES = f"{ROOT}/data/profiles/business_profiles.csv"

OUT_BUSINESS_EMB = f"{ROOT}/data/profiles/business_embeddings.csv"
OUT_USER_EMB = f"{ROOT}/data/profiles/user_embeddings.csv"

AGGREGATION_STRATEGY = "recency"      # "mean" | "recency"
DECAY_CONSTANT_DAYS = 30.0         # only used when AGGREGATION_STRATEGY == "recency"
MIN_REVIEWS_BUSINESS = 5
MIN_REVIEWS_USER = 3
APPLY_COLDSTART_BLEND = True       # businesses only -- see aggregation.py

MAX_TFIDF_FEATURES = 20000
TFIDF_NGRAM_RANGE = (1, 2)
TOP_N_LABEL_TERMS = 6


def main():
    print(f"Aggregation strategy: {AGGREGATION_STRATEGY}")
    print("Loading per-review embeddings + meta ...")
    review_embeddings = np.load(REVIEW_EMBEDDINGS_NPY, mmap_mode="r")
    meta = pd.read_csv(REVIEW_EMBEDDINGS_META)
    print(f"  {len(meta):,} reviews, dim={review_embeddings.shape[1]}")

    print("Loading review text for TF-IDF ...")
    text_df = pd.read_parquet(REVIEWS_PARQUET, columns=["review_id", "text"])
    text_df = text_df.set_index("review_id").loc[meta["review_id"]].reset_index()
    text_df["text"] = text_df["text"].fillna("")
    assert len(text_df) == len(meta), "review text failed to align 1:1 with meta"

    print(f"Fitting TF-IDF (max_features={MAX_TFIDF_FEATURES}, ngram_range={TFIDF_NGRAM_RANGE}) ...")
    vectorizer, tfidf_matrix = fit_tfidf(text_df["text"], max_features=MAX_TFIDF_FEATURES,
                                          ngram_range=TFIDF_NGRAM_RANGE)
    feature_names = vectorizer.get_feature_names_out()

    print("Building business profiles ...")
    biz_profiles = build_group_profiles(
        review_embeddings, meta, group_col="business_id",
        strategy=AGGREGATION_STRATEGY, min_reviews=MIN_REVIEWS_BUSINESS,
        decay_constant=DECAY_CONSTANT_DAYS,
    )
    n_low_conf_biz = int(biz_profiles["low_confidence"].sum())
    print(f"  {len(biz_profiles):,} businesses, {n_low_conf_biz:,} low-confidence "
          f"(< {MIN_REVIEWS_BUSINESS} reviews)")

    biz_labels = build_group_labels(
        tfidf_matrix, meta, group_col="business_id", feature_names=feature_names,
        strategy=AGGREGATION_STRATEGY, decay_constant=DECAY_CONSTANT_DAYS,
        top_n=TOP_N_LABEL_TERMS,
    )
    biz_profiles = biz_profiles.merge(biz_labels, on="business_id", how="left")

    if APPLY_COLDSTART_BLEND:
        if n_low_conf_biz == 0:
            print("  no low-confidence businesses to blend -- skipping "
                  "(see KNOWN CAVEAT in this file's docstring)")
        else:
            print("  blending low-confidence business profiles with category priors ...")
            biz_meta = pd.read_csv(BUSINESS_PROFILES, usecols=["business_id", "categories"])
            category_by_id = dict(zip(biz_meta.business_id, biz_meta.categories))
            biz_profiles = blend_with_category_prior(
                biz_profiles, category_by_id, min_reviews=MIN_REVIEWS_BUSINESS,
            )

    biz_profiles.to_csv(OUT_BUSINESS_EMB, index=False)
    print(f"Saved: {OUT_BUSINESS_EMB}")

    print("Building user profiles ...")
    user_profiles = build_group_profiles(
        review_embeddings, meta, group_col="user_id",
        strategy=AGGREGATION_STRATEGY, min_reviews=MIN_REVIEWS_USER,
        decay_constant=DECAY_CONSTANT_DAYS,
    )
    n_low_conf_user = int(user_profiles["low_confidence"].sum())
    print(f"  {len(user_profiles):,} users, {n_low_conf_user:,} low-confidence "
          f"(< {MIN_REVIEWS_USER} reviews) -- flagged only, no category concept "
          f"for users so no blending is applied")

    user_labels = build_group_labels(
        tfidf_matrix, meta, group_col="user_id", feature_names=feature_names,
        strategy=AGGREGATION_STRATEGY, decay_constant=DECAY_CONSTANT_DAYS,
        top_n=TOP_N_LABEL_TERMS,
    )
    user_profiles = user_profiles.merge(user_labels, on="user_id", how="left")

    user_profiles.to_csv(OUT_USER_EMB, index=False)
    print(f"Saved: {OUT_USER_EMB}")


if __name__ == "__main__":
    main()
